### PR TITLE
Fixed groupedquery_attention typo

### PR DESCRIPTION
**Pull request by mvpatel2000**
Renamed groupedquery_attention to match multiquery_*

### CODE REVIEW

**Comment by dakinggg** [comment]
the docs match the old string. why are you changing this?

**Comment by mvpatel2000** [comment]
> the docs match the old string. why are you changing this?

image
isn't this weird?

which docs? I can also update or discuss offline

**Comment by vchiley** [comment]
For to match `multiquery` and `multihead`?

**Comment by mvpatel2000** [comment]
> For to match `multiquery` and `multihead`?

Yes. Updated PR description to be more clear. I guess not obvious. Maybe only my OCD :P.

**Comment by dakinggg** [comment]
ok sure, no problem changing. docs are in `configuration_mpt.py`

**Comment by mvpatel2000** [comment]
@sashaDoubov I will remember this

**Pull request closed without merging**
