### PR TITLE
Adding Simplified Coding Tasks

### PR DESCRIPTION
**Pull request by mcarbin**
Ran coding tasks on 3b model: `coding-eval-Tzea5x`

```
| Category   | Benchmark                 | Subtask   |   Accuracy | Number few shot   | Model        |
|:-----------|:--------------------------|:----------|-----------:|:------------------|:-------------|
|            | human_eval                |           | 0.00762195 | 0-shot            | mosaicml/30b |
|            | human_eval_cpp            |           | 0.00341615 | 0-shot            | mosaicml/30b |
|            | human_eval_js             |           | 0.00640244 | 0-shot            | mosaicml/30b |
|            | human_eval_return_simple  |           | 0.210811   | 0-shot            | mosaicml/30b |
|            | human_eval_return_complex |           | 0.0330709  | 0-shot            | mosaicml/30b |
|            | human_eval_25             |           | 0.00579268 | 0-shot            | mosaicml/30b |
|            | human_eval_50             |           | 0.017378   | 0-shot            | mosaicml/30b |
|            | human_eval_75             |           | 0.0646342  | 0-shot            | mosaicml/30b |
```

### CODE REVIEW

**Comment by bmosaicml** [comment]
Rather than create a new yaml describing these tasks, would you mind just adding them to the existing yamls alongside the original human eval datasets? namely the tasks.yaml file

**Comment by bmosaicml** [comment]
Cody I'd like to kick off an eval of this, do you have a 3B model I could run it against?

**Comment by samhavens** [comment]
Since these are new tasks that we came up with, is there anywhere we could give a short description of what the `.25`, `return-simple` etc mean?

**Review by samhavens — APPROVED** [review]
thanks for adding links to the more obscure data sets

**Review by bmosaicml — APPROVED** [review]

**Pull request merged**
