### PR TITLE
add `load_strict_model_weights` as an optional config parameter

### PR DESCRIPTION
**Pull request by AllenHW**
The parameter is already exposed in `composer.Trainer`. This change will expose it via `train.py` in llm-foundry

### CODE REVIEW

**Review by dakinggg — APPROVED** [review]
Thanks Allen!

**Comment by dakinggg** [comment]
You'll need to run `pre-commit` to get the linting to pass. Let me know if you run into any issues there!

**Comment by dakinggg** [comment]
Hey @AllenHW looks like I can't update your branch to main for you. If you could do that, it should auto merge after CI passes!

**Comment by AllenHW** [comment]
@dakinggg Sorry, I forgot to loop back to this last week. Thanks for helping merge this.

**Pull request merged**
