### PR TITLE
Bump composer to 0.24.1 + FSDP config device_mesh deprecation

### PR DESCRIPTION
**Pull request by snarayan21**
Bump composer to 0.24.1, and as part of that, we replace parts of code that assume `device_mesh` is a key specified in the fsdp_config dict.

Added unit test for correct fsdp_config --> ffn_config device mesh parsing

This also resolves issues we were seeing with not using device mesh in regression tests.
Successfully reran failing regressions, which succeeded.

### CODE REVIEW

**Review by mvpatel2000 — COMMENTED** [review]
should be 24.1?

**Comment by snarayan21** [comment]
@mvpatel2000 nah I haven't cut the newest composer release yet. I mean this PR can wait until then, but taking out device mesh completely is 0.24.0 onwards

**Review by dakinggg — COMMENTED** [review]
Might as well wait for 0.24.1 just to make it one PR, but LGTM

**Comment by snarayan21** [comment]
@mvpatel2000 @dakinggg composer v0.24.1 is out so updated this PR. should be good to go

**Review by dakinggg — APPROVED** [review]

**Pull request merged**
