### PR TITLE
Add InvalidConversationError

### PR DESCRIPTION
**Pull request by b-chu**
Adds a new UserError for when the conversation can't be correctly sliced

### CODE REVIEW

**Review by milocress — APPROVED** [review]

**Review by mvpatel2000 — COMMENTED** [review]
Should this require a unit test?

**Review by dakinggg — COMMENTED** [review]
could you dig a little deeper? I don't think this error should ever be hit. how does it happen?

**Comment by b-chu** [comment]
conversation_through_previous_turn ends in `<|eot_id|><|start_header_id|>assistant<|end_header_id|>`

the corresponding part in full_conversation ends in `<|eot_id|><|start_header_id|>user<|end_header_id|>`

**Comment by b-chu** [comment]
The conversation goes system, user, assistant, user, assistant, assistant and I think we require alternating user and assistant

**Pull request merged**
