### PR TITLE
Do not consider run_name when auto-detecting autoresume

### PR DESCRIPTION
**Pull request by irenedea**
Removes the consideration for run_name as there is already a default

### CODE REVIEW

**Review by dakinggg — COMMENTED** [review]
Why do we want to deprecate this? I thought we could just remove the run_name condition since run_name has a default.

**Comment by irenedea** [comment]
ah, I may have understood what we discussed. I think it's odd to automatically switch to autoresume when run name is set, so we should deprecate this feature entirely.

**Comment by irenedea** [comment]
I'm fine with keeping it as is (or making the change you suggested). I don't feel strongly and this would certainly eventually break some runs.

**Comment by dakinggg** [comment]
The intention of this feature is that, generally speaking, you want autoresume to be on. The reason you would not want to do this is if you were sharing a save_folder between runs, so the condition was just trying to be a little safe about it. but we still want to set it to true in most cases.

**Review by dakinggg — APPROVED** [review]

**Pull request merged**
