### PR TITLE
Add Model sharding support with deepspeed

### PR DESCRIPTION
**Pull request by vivekgoe**
In order to execute large models (MPT-30B, MPT-70B) with Deepspeed Zero-3 only, model parameters need to be sharded across devices during loading itself. Added call to deepspeed.zero.Init() to achieve this parameter sharding.

### CODE REVIEW

**Comment by vivekgoe** [comment]
@abhi-mosaic please help review this and merge it to habana_alpha branch. Please note that with this change we need to use SynapseAI release >= 1.13.0

**Review by abhi-mosaic — COMMENTED** [review]
Hi @vivekgoe , sorry for the long overdue review. These changes look good to me, and trust that you've tested this on Gaudi2.

Re. the use of `deepspeed_config['zero_optimization']['stage'] == 3:`, does this work on multinode now on Synapse >= 1.13?

Lastly, could you review the Intel Gaudi README notes here and edit in case anything is outdated? https://github.com/mosaicml/llm-foundry/blob/habana_alpha/README.md#intel-gaudi

Once I hear back I will approve and merge.

**Comment by vivekgoe** [comment]
@abhi-mosaic  yes these changes are tested on Gaudi2 for MPT-70B on 32x Gaudi2 with Synapse >= 1.13.  Regarding Intel Gaudi README, we can modify (5) in list of known limitations to "Initialization and execution of large models (e.g. MPT-30B, MPT-70B etc.) with DeepSpeed Zero3 require setting environment variable DEEPSPEED_HPU_ZERO3_SYNC_MARK_STEP_REQUIRED=1, this limitation shall be removed in future releases".

**Comment by abhi-mosaic** [comment]
Thank you @vivekgoe !

**Pull request merged**
