### PR TITLE
Warn instead of error on tokenizer-only download with http

### PR DESCRIPTION
**Pull request by jerrychen109**
When download from HTTP is specified with `tokenizer-only`, let's just warn that all files will be downloaded from the file server path rather than erroring out entirely.

### CODE REVIEW

**Review by nancyhung — APPROVED** [review]
can you test that this fixes the issue before merging in and link the run name in the PR description?

**Review by irenedea — APPROVED** [review]
LGTM, @jerrychen109 do you still want to merge this?

**Comment by jerrychen109** [comment]
Oops yeah let me quickly re-run for proof that it still works

**Comment by jerrychen109** [comment]
Tested on r12z3 interactive after cloning this branch:
image

Compared to main branch without this change:
image

**Pull request merged**
